apiVersion: v2
name: wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 1.0.0
appVersion: "0.33.0"
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  # - name: redis
  #   version: 17.11.3
  #   repository: https://charts.bitnami.com/bitnami
  #   condition: redis.install
  - name: app
    version: "*.*.*"
    repository: file://charts/app
    condition: app.install
  # - name: weave
  #   version: "*.*.*"
  #   repository: file://charts/weave
  #   condition: weave.install
  # - name: console
  #   version: "*.*.*"
  #   repository: file://charts/console
  #   condition: console.install
