## NOTICE
#
# Due to the scope and complexity of this chart, all possible values are not
# documented in this file. Extensive documentation is available.
#
# Because properties are regularly added, updated, or relocated, it is _strongly
# suggest_ to not "copy and paste" this YAML. Please provide Helm only those
# properties you need, and allow the defaults to be provided by the version of
# this chart at the time of deployment.

# The global properties are used to configure multiple charts at once.
global:
  common:
    labels: {}
    annotations: {}
  ## Supplemental Pod labels. Will not be used for selectors.
  pod:
    labels: {}
    annotations: {}
  deployment:
    annotations: {}
    labels: {}
  service:
    labels: {}
    annotations: {}

  extraEnvFrom: {}
  extraEnv: {}

  mysql:
    host: "my.database.com"
    port: 3306
    auth:
      database: "wandb"
      user: ""
      password: ""
      # Use existing secret for password details. The secret has to contain the
      # key `mysql-password`
      existingSecret: ""

  hosts:
    domain: domain.com
    https: false

  sso:
    openid:
      enabled: false
    ldap:
      enabled: false

  storage:
    enable: false
    connectionString: ""
    aws:
      region: "us-west-1"
      encryption: aws:kms
      encryptionKmsKeyArn: arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab

app:
  image:
    repository: wandb/local
    tag: latest

nameOverride: ""
fullnameOverride: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 0

## Installation & configuration of stable/redis
## See Chart.yaml for current version
redis:
  install: true
  auth:
    password: "wandb-redis-password"
  architecture: standalone
  cluster:
    enabled: false
  metrics:
    enabled: true

## Installation & configuration of stable/mysql
## See Chart.yaml for current version
mysql:
  install: true
  port: 3306
