# Default values for wandb.
image:
  repository: wandb/local
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Required for production environments
license:
# If set to true we'll provision an admin user and allow admin api access
enableAdminApi: false
# If using S3 be sure the pod has valid IAM creds, if using minio
# you can include the creds in the bucket url, i.e.
# !!! Be sure to use the externally accessible host / ingress,
# not the internal service
# s3://$ACCESS_KEY_ID:$SECRET_KEY@$HOST/$BUCKET?tls=true
bucket:
bucketRegion: us-east-1
# If you use a custom KMS key for bucket encryption specify the arn here
bucketKmsKeyArn:
# We use sendgrid.com by default to send emails, but you can specify your own smtp server
smtpServer:
# when setting up an ingress, set this to http://domain.com or https://domain.com
host:
# If you aren't connected to an external bucket and want to mount a custom claim for minio
existingClaim:

# set additional env variables
extraEnv:
# - name: AWS_SECRET_ACCESS_KEY
#   value: XXX

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# dns hostAliases, generally only used in development
hostAliases: []
# Custom CA's to make SSL verification work for self signed certs
# You'll likely want to use `--set-file customCACerts={/path/to/rootCA.crt}`
customCACerts: []

serviceAccount:
  create: true
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 0
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 0

service:
  type: ClusterIP
  port: 8080

sso:
  enabled: false
  # Automatically provision a user if SSO auth succeeds
  autoProvision: true
  issuer:
  # Can be implicit or pkce
  method: implicit
  clientId:
  # Optional, only if your IDP requires it
  clientSecret:

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: wandb.mycompany.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 1000m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  # Set this to false if you want to bring your own mysql
  managed: true
  # If you have an existing mysql host, specify the host, user, and password here
  host:
  user:
  password:
  database:
  command:
  image:
    pullPolicy: IfNotPresent
    repository: mysql/mysql-server
    tag: "8.0"
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
  service:
    ## Specify a service type
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 64Gi
    # If you want to re-use an existing pv claim
    existingClaim:
    annotations: {}
