agent:
  # W&B API key.
  apiKey: ""
  # Container image to use for the agent.
  image: wandb/launch-agent-dev:latest
  # Image pull policy for agent image.
  imagePullPolicy: Always
  # Resources block for the agent spec.
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

namespace: wandb-launch

# This should be set to the literal contents of your launch agent config.
launchConfig:
   # URL of your W&B server. Defaults to https://api.wandb.ai
  base_url: https://api.wandb.ai

  # W&B entity (i.e. user or team) name
  entity: <entity-name>

  # Max number of concurrent runs to perform. -1 = no limit
  max_jobs: -1

  # List of queues to poll.
  queues:
  - default

  # Cloud environment config.
  environment:
    type: local #aws|gcp

  # Container registry config.
  registry:
    type: local #ecr|gcr

  # Container build config.
  builder:
    type: docker #kaniko|noop

# Set to false to disable volcano install.
volcano: true

# The contents of a git credentials file. This will be stored in a k8s secret
# and mounted into the agent container. Set this if you want to clone private
# repos.
gitCreds: |

# Annotations for the wandb service account. Useful when setting up workload identity on gcp.
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account:
