agent:
  labels: {}
  # W&B API key.
  apiKey: ""
  # Container image to use for the agent.
  image: wandb/launch-agent-dev:latest
  # Image pull policy for agent image.
  imagePullPolicy: Always
  # Resources block for the agent spec.
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

# This should be set to the literal contents of your launch agent config.
launchConfig: |

# Set to false to disable volcano install.
volcano: true

# The contents of a git credentials file. This will be stored in a k8s secret
# and mounted into the agent container. Set this if you want to clone private
# repos.
gitCreds: |

# Annotations for the wandb service account. Useful when setting up workload identity on gcp.
serviceAccount:
  annotations:

# Set to access key for azure storage if using kaniko with azure.
azureStorageAccessKey: ""
