apiVersion: v2
name: prometheus
type: application
description: A Helm chart for Kubernetes

version: 0.1.0
appVersion: "1.0.0"

home: https://wandb.ai
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: mysql-exporter
    version: "*.*.*"
    repository: file://charts/mysql-exporter
    condition: mysql-exporter.install
  - name: node-exporter
    version: "*.*.*"
    repository: file://charts/node-exporter
    condition: node-exporter.install
