apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.fullname" . }}-data
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "mysql.commonLabels" . | nindent 4 }}
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if (ne "" .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- else if (ne "" .Values.global.storageClassName) }}
  storageClassName: "{{ .Values.global.storageClassName }}"
  {{- else }}
  storageClassName: ""
  {{- end }}