apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  ACCESS_KEY: {{ .Values.global.bucket.accessKey | b64enc }}
  SECRET_KEY: {{ .Values.global.bucket.secretKey | b64enc }}