apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "wandb.bucket.config" . }}"
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  BUCKET: {{ include "wandb.bucket" .url | b64enc }}
  AWS_REGION: {{ include "wandb.bucket" .region | b64enc }}
  AWS_S3_KMS_ID: {{ include "wandb.bucket" .kmsKey | b64enc }}

{{- if not .Values.global.bucket.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  {{ include "wandb.bucket" .accessKeyName }}: {{ .Values.global.bucket.accessKey | default .Values.global.defaultBucket.accessKey | b64enc }}
  {{ include "wandb.bucket" .secretKeyName }}: {{ .Values.global.bucket.secretKey | default .Values.global.defaultBucket.secretKey | b64enc }}
{{- end }}
