{{- if not .Values.global.bucket.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  ACCESS_KEY: {{ .Values.global.bucket.accessKey | default .Values.global.defaultBucket.accessKey | b64enc }}
  SECRET_KEY: {{ .Values.global.bucket.secretKey | default .Values.global.defaultBucket.secretKey | b64enc }}
{{- end }}