{{- if not (include "wandb.resolved.bucket" .secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  ACCESS_KEY: {{ include "wandb.resolved.bucket" .accessKey | b64enc }}
  SECRET_KEY: {{ include "wandb.resolved.bucket" .secretKey | b64enc }}
{{- end }}
