apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wandb.bucket.config" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
  {{- if .Values.settingsMigrationHook.install }}
  {{- with .Values.global.settingsMigrationHook.helmHookAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
data:
{{- with include "wandb.bucket" . | fromYaml }}
  BUCKET_NAME: "{{ .name }}"
  BUCKET_PATH: "{{ .path }}"
  AWS_REGION: "{{ .region }}"
  AWS_S3_KMS_ID: "{{ .kmsKey }}"
{{- end }}
{{- if not .Values.global.bucket.secret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
  {{- if .Values.settingsMigrationHook.install }}
  {{- with .Values.global.settingsMigrationHook.helmHookAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
data:
{{- with include "wandb.bucket" . | fromYaml }}
  {{- if .accessKey }}
  {{ .accessKeyName }}: {{ .accessKey | b64enc }}
  {{- end }}
  {{- if .secretKey }}
  {{ .secretKeyName }}: {{ .secretKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
