apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wandb.bucket.config" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
{{- with include "wandb.bucket" . | fromYaml }}
  BUCKET_NAME: {{ .name | quote }}
  BUCKET_PATH: {{ .path | quote }}
  AWS_REGION: {{ .region | quote }}
  AWS_S3_KMS_ID: {{ .kmsKey | quote }}
{{- end }}
{{- if not .Values.global.bucket.secret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.bucket.secret" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
{{- with include "wandb.bucket" . | fromYaml }}
  {{- if .accessKey }}
  {{ .accessKeyName }}: {{ .accessKey | b64enc }}
  {{- end }}
  {{- if .secretKey }}
  {{ .secretKeyName }}: {{ .secretKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
