apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca-certs
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data:
  {{- range $index, $pem := .Values.global.customCACerts }}
  customCA{{$index}}.crt: |-
    {{- range splitList "\n" $pem }}
    {{ . }}
    {{- end }}
  {{- end }}
