---
{{- $secretName := (include "wandb.clickhouse.passwordSecret" .)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  CLICKHOUSE_PASSWORD: {{ include "wandb.clickhouse.password" . | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  CLICKHOUSE_HOST: {{ .Values.global.clickhouse.host | quote }}
  CLICKHOUSE_PORT: {{ .Values.global.clickhouse.port | quote }}
  CLICKHOUSE_DATABASE: {{ .Values.global.clickhouse.database | quote }}
  CLICKHOUSE_USER: {{ .Values.global.clickhouse.user | quote }}
