kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog-agent
spec:
  global:
    site: {{ .Values.datadog.site }}
    credentials:
      apiKey: {{ .Values.datadog.dd_api_key }}
      appKey: {{ .Values.datadog.dd_app_key }}
  features:
    externalMetricsServer:
      enabled: true
      useDatadogMetrics: false
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
