kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    site: {{ .Values.datadog.site }}
    credentials:
      apiKey: {{ .Values.datadog.apiKey }}
      appKey: {{ .Values.datadog.appKey }}
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
