apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-global-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.global.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

