apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-glue
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-glue
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  GORILLA_GLUE_TASK_PROVIDER: "memory://"
  GORILLA_GLUE_TASK_CONFIG_PATH: "/gorilla_glue_tasks_local.yaml"
  GORILLA_GLUE_TASK_STORE: "memory://"
