{{- if .Values.ingress.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.ingress.issuer.server | quote }}
    email: {{ .Values.ingress.issuer.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-acme-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.class }}
{{- end }}
{{- if .Values.ingress.install }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default .Release.Name .Values.ingress.nameOverride }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- if .Values.ingress.labels -}}
    {{-   toYaml .Values.ingress.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.issuer.create }}
    "cert-manager.io/issuer": "{{ .Release.Name }}-issuer"
    "cert-manager.io/acme-challenge-type": "http01"
    "kubernetes.io/ingress.allow-http" : "false"
    {{- end }}

    {{- if .Values.ingress.annotations -}}
    {{-   toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- $defaultHost := include "defaultHost" . -}}

  {{- if .Values.ingress.issuer.create }}
  tls:
    - host: [{{ $defaultHost }}]
      secretName: {{ .Release.Name }}-tls
  {{- else }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}

  rules:
  {{- range concat (list $defaultHost) .Values.ingress.additionalHosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            {{- if eq $.Values.ingress.defaultBackend "console" }}
            name: {{ $.Release.Name }}-console
            port:
              number: 8082
            {{- else }}
            name: {{ $.Release.Name }}-app
            port: 
              number: 8080
            {{- end }}
      - pathType: Prefix
        path: /console
        backend:
          service:
            name: {{ $.Release.Name }}-console
            port:
              number: 8082
  {{- end }}
{{- end }}
