---
{{- $secretName := .Values.kafka.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  {{- $secretValue := "" }}
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (printf "%s" $secretName)).data }}
  {{- if and $secretData (hasKey $secretData "client-passwords")}}
    {{- $secretValue = index $secretData "client-passwords" }}
  {{- end }}
  {{- if or (empty $secretValue) (not (eq (len .Values.kafka.client.users) (len (splitList "," (b64dec $secretValue))))) }}
    {{- $clientPasswords := .Values.kafka.client.passwords }}
    {{- if empty $clientPasswords }}
      {{- $clientPasswords = list }}
      {{- range .Values.kafka.client.users }}
        {{- $clientPasswords = append $clientPasswords (randAlphaNum 10) }}
      {{- end }}
    {{- end }}
    {{- $secretValue = join "," $clientPasswords | toString | b64enc }}
  {{- end }}
  client-passwords: {{ $secretValue | quote }}
  system-user-password: {{ index (splitList "," (b64dec $secretValue)) 0 | b64enc | quote }}
  
  {{- $brokerSecretValue := "" }}
  {{- if and $secretData (hasKey $secretData "inter-broker-password")}}
    {{- $brokerSecretValue = index $secretData "inter-broker-password" }}
  {{- end }}
  {{- if empty $brokerSecretValue }}
    {{- $brokerPassword := .Values.kafka.broker.password }}
    {{- if empty $brokerPassword }}
      {{- $brokerPassword = randAlphaNum 10 }}
    {{- end }}
    {{- $brokerSecretValue = $brokerPassword | b64enc | quote }}
  {{- end }}
  inter-broker-password: {{ $brokerSecretValue }}

  {{- $controllerSecretValue := "" }}
  {{- if and $secretData (hasKey $secretData "controller-password")}}
    {{- $controllerSecretValue = index $secretData "controller-password" }}
  {{- end }}
  {{- if empty $controllerSecretValue }}
    {{- $controllerPassword := .Values.kafka.controller.password }}
    {{- if empty $controllerPassword }}
      {{- $controllerPassword = randAlphaNum 10 }}
    {{- end }}
    {{- $controllerSecretValue = $controllerPassword | b64enc | quote }}
  {{- end }}
  controller-password: {{ $controllerSecretValue }}

  {{- $kraftSecretValue := "" }}
  {{- if and $secretData (hasKey $secretData "kraft-cluster-id")}}
    {{- $kraftSecretValue = index $secretData "kraft-cluster-id" }}
  {{- end }}
  {{- if empty $kraftSecretValue }}
    {{- $kraftId := .Values.kafka.kraft.id }}
    {{- if empty $kraftId }}
      {{- $kraftId = randAlphaNum 22 }}
    {{- end }}
    {{- $kraftSecretValue = $kraftId | b64enc | quote }}
  {{- end }}
  kraft-cluster-id: {{ $kraftSecretValue }}
