{{- $secretName := (include "wandb.kafka.passwordSecret" .)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  KAFKA_CLIENT_PASSWORD: {{ include "wandb.kafka.password" . | b64enc }}