{{- if eq .Values.ingress.use "nginx" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;

        location / {
          proxy_pass http://{{ .Release.Name }}-app;
        }

        location /console {
          proxy_pass http://{{ .Release.Name }}-console;
        }
      }
    }
{{- end }}