apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  GORILLA_PARQUET_RPC_PATH: "/_goRPC_"
  GORILLA_PARQUET_PORT: "8087"
  PARQUET_ENABLED: "true"