{{- if not .Values.redis.install }}
{{- $secretName := (include "wandb.redis.passwordSecret" .)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  REDIS_PASSWORD: {{ include "wandb.redis.password" . | b64enc }}
  REDIS_CA_CERT: {{ include "wandb.redis.caCert" . | b64enc }}
{{- end }}
