{{- if .Values.settingsMigrationJob.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smj-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:
  SMJ_DEBUG: {{ .Values.global.settingsMigrationJob.debug | quote }}
  SMJ_DRY_RUN: {{ .Values.global.settingsMigrationJob.dryRun | quote }}
  {{- with include "wandb.bucket" . | fromYaml }}
  AWS_REGION: "{{ .region }}"
  AWS_S3_KMS_ID: "{{ .kmsKey }}"
  {{- end }}
{{- end }}
