apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-weave
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-weave
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  WEAVE_SERVICE: "{{ .Release.Name }}-weave:9994"
  {{- if index .Values.global "weave-trace" "enabled" }}
  WEAVE_TRACES_ENABLED: "true"
  {{- end }}