apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: wandb
    wandb.ai/console-default: "true"
  name: wandb
  namespace: default
spec:
  values:
    global:
      host: "http://wandb.lab.local"
      license: "your-license-key"
      mysql:
        host: "mysql.lab.local"
        port: 3306
        database: "wandb"
        user: "wandb"
        password: "password"
      bucket:
        provider: "s3"
        name: "minio.lab.local:9000"
        path: "wandb"
        region: "eu-central-1"
        kmsKey:
        secretKey: "your-secret-key"
        accessKey: "your-access-key"
    mysql:
      install: false
    app:
      install: true
      image:
        repository: "wandb/local"
        tag: 0.45.0
      extraEnv:
        SUPPORTED_FILE_STORES: ""
    ingress:
      annotations:
        # This configuration is based on Nginnx Ingress Controller
        nginx.ingress.kubernetes.io/proxy-body-size: "64m"
      class: "nginx"
    otel:
      install: true
    parquet:
      install: true
    weave:
      provider: "onprem"
      persistence:
        accessMode: "ReadWriteOnce"
    redis:
      install: true
    prometheus:
      install: true
