apiVersion: v2
name: operator-wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.15.5
appVersion: 1.0.0
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: app
    version: "*.*.*"
    repository: file://charts/app
    condition: app.install
  - name: console
    version: "*.*.*"
    repository: file://charts/console
    condition: console.install
  - name: weave
    version: "*.*.*"
    repository: file://charts/weave
    condition: weave.install
  - name: weave-trace
    version: "*.*.*"
    repository: file://charts/weave-trace
    condition: weave-trace.install
  - name: parquet
    version: "*.*.*"
    repository: file://charts/parquet
    condition: parquet.install
  - name: mysql
    version: "*.*.*"
    repository: file://charts/mysql
    condition: mysql.install
  - name: prometheus
    version: "*.*.*"
    repository: file://charts/prometheus
    condition: prometheus.install
  - name: redis
    version: "18.*.*"
    condition: redis.install
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: "25.*.*"
    condition: kafka.install
    repository: https://charts.bitnami.com/bitnami
  - name: otel
    version: "*.*.*"
    repository: file://charts/otel
    condition: otel.install
  - name: flat-run-fields-updater
    version: "*.*.*"
    repository: file://charts/flat-run-fields-updater
    condition: flat-run-fields-updater.install
  - name: nginx
    version: "*.*.*"
    repository: file://charts/nginx
    condition: nginx.install
  - name: stackdriver
    version: "*.*.*"
    repository: file://charts/stackdriver
    condition: stackdriver.install
  - name: yace
    version: "*.*.*"
    repository: file://charts/yace
    condition: yace.install
