apiVersion: v2
name: operator-wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.10.10
appVersion: 1.0.0
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: app
    version: "*.*.*"
    repository: file://charts/app
    condition: app.install
  - name: console
    version: "*.*.*"
    repository: file://charts/console
    condition: console.install
  - name: weave
    version: "*.*.*"
    repository: file://charts/weave
    condition: weave.install
  - name: parquet
    version: "*.*.*"
    repository: file://charts/parquet
    condition: parquet.install
  - name: mysql
    version: "*.*.*"
    repository: file://charts/mysql
    condition: mysql.install
  - name: prometheus
    version: "*.*.*"
    repository: file://charts/prometheus
    condition: prometheus.install
  - name: redis
    version: "18.*.*"
    repository: https://charts.bitnami.com/bitnami
