apiVersion: v2
name: operator-wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: app
    version: "*.*.*"
    repository: file://charts/app
    condition: app.install
  - name: console
    version: "*.*.*"
    repository: file://charts/console
    condition: console.install
  - name: weave
    version: "*.*.*"
    repository: file://charts/weave
    condition: weave.install
  - name: mysql
    version: "*.*.*"
    repository: file://charts/mysql
    condition: mysql.install
