{{- $secretName := printf "%s-secrets" (include "weaveTrace.name" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaveTrace.name" . }}-dangerzone-secrets
type: Opaque
data:
  WEAVE_TRACE_GORILLA_JWT_SECRET: {{ if $existingSecret }}
    {{ $existingSecret.data.WEAVE_TRACE_GORILLA_JWT_SECRET }}
  {{ else }}
    {{ randAlphaNum 32 | b64enc }}
  {{ end }}