{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weaveTrace.serviceAccountName" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- if .Values.global."weave-trace".serviceAccount.labels -}}
    {{-   toYaml .Values.global."weave-trace".serviceAccount.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global."weave-trace".serviceAccount.annotations -}}
    {{-   toYaml .Values.global."weave-trace".serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}
