apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weave-trace.weaveTrace.serviceAccountName" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- $weaveLabels := index .Values.global "weave-trace" "serviceAccount" "labels" }}
    {{- if $weaveLabels -}}
    {{-   toYaml $weaveLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- $weaveAnnotations := index .Values.global "weave-trace" "serviceAccount" "annotations" }}
    {{- if $weaveAnnotations -}}
    {{-   toYaml $weaveAnnotations | nindent 4 }}
    {{- end }}
