{{- if .Values.serviceAccount.create -}}
{{- if (empty .Values.global.weave-trace.serviceAccountName) -}}
{{- fail "Values.global.weave-trace.serviceAccountName cannot be empty if serviceAccount.create is true" -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.weave-trace.serviceAccountName }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels -}}
    {{-   toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations -}}
    {{-   toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}
