{{- if .Values.discoverZoneFromNode }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bufstream.name" . }}-node-reader
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.bufstream.serviceAccount.name }}
  namespace: {{ include "bufstream.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "bufstream.name" . }}-node-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
