{{- if .Values.discoverZoneFromNode }}
# A role for bufstream to read the zone label on the node it's running.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bufstream.name" . }}-node-reader
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
{{- end }}
