apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bufstream.name" . }}-config
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{- include "bufstream.config" . | nindent 4 -}}
