{{- if .Values.bufstream.controlServerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bufstream.controlServerServiceName" . }}
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
  {{- with .Values.bufstream.controlServerService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: {{ include "bufstream.containerPort" "connect" }}
  selector:
  {{- include "bufstream.selectorLabels" . | nindent 4 }}
{{- end }}
