{{- if .Values.bufstream.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bufstream.name" . }}
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.bufstream.deployment.kind | default "Deployment" }}
    name: {{ include "bufstream.name" . }}
  minReplicas: {{ .Values.bufstream.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.bufstream.deployment.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.bufstream.deployment.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.bufstream.deployment.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.bufstream.deployment.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bufstream.deployment.autoscaling.targetCPU }}
    {{- end }}
  {{- if .Values.bufstream.deployment.autoscaling.behavior }}
  behavior: {{ toYaml .Values.bufstream.deployment.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
