{{- if .Values.bufstream.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bufstream.name" . }}
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
spec:
  {{- with .Values.bufstream.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.bufstream.podDisruptionBudget.minAvailable | default 0 }}
  {{- end }}
  selector:
  {{- include "bufstream.selectorLabels" . | nindent 4 }}
{{- end }}
