{{- if .Values.bufstream.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.bufstream.serviceAccount.name }}
  namespace: {{ include "bufstream.namespace" . }}
  labels:
    {{- include "bufstream.labels" . | nindent 4 }}
  {{- with .Values.bufstream.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
