extends: default

rules:
  new-line-at-end-of-file: enable
  document-end: disable
  line-length: disable
  trailing-spaces: enable
  braces: disable
  indentation: disable
  document-start: disable
  hyphens: disable
