enabled: true

nameOverride: ""
fullnameOverride: ""

regions: 

image:
  registry: ghcr.io
  repository: nerdswords/yet-another-cloudwatch-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.60.0

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

service:
  type: ClusterIP
  annotations: {}

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  
deployment: {}
serviceAccount: {}

common:
  labels: {}
  annotations: {}

configMap:
  labels: {}
  annotations: {}

resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi
