enabled: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/local
  tag: latest
  pullPolicy: Always
  # pullSecrets: []

glueSingleton:
  enabled: false

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 1

# Tolerations for pod scheduling
tolerations: []

traceRatio: 0

extraEnv: {}
extraEnvFrom: {}

extraCors: []

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

common:
  labels: {}

deployment:
  labels: {}
  annotations: {}

service:
  type: ClusterIP
  annotations: {}
  labels: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a
  # conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 8Gi

serviceAccount:
  create: true
  annotations: {}

role: {}
roleBinding: {}

# Optional artifacts garbage collection settings.
# If these are not set, the default values from glue_tasks_local.yaml will be used.
artifactsGc:
  BatchSize: 0
  NumWorkers: 0
  DeleteFilesNumWorkers: 0

# internalJWTMap is used to map service accounts to their issuers.
internalJWTMap:
  - subject: "system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}-weave-trace"
    issuer: ""
