---
{{- if .Values.clearCache.enabled -}}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "weave.fullname" . }}-cache-clear
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
    {{- if .Values.clearCache.labels -}}
    {{-   toYaml .Values.clearCache.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.clearCache.annotations -}}
    {{-   toYaml .Values.clearCache.annotations | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ .Values.clearCache.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "wandb.podLabels" . | nindent 12 }}
            {{- include "weave.commonLabels" . | nindent 12 }}
            {{- include "weave.podLabels" . | nindent 12 }}
            {{- include "weave.labels" . | nindent 12 }}
          annotations:
            {{- if .Values.pod.annotations -}}
            {{-   toYaml .Values.pod.annotations | nindent 4 }}
            {{- end }}
        spec:
          {{- if .tolerations }}
          tolerations:
            {{- toYaml .tolerations | nindent 12 }}
          {{- end }}
          {{- include "wandb.nodeSelector" . | nindent 10 }}
          {{- include "wandb.priorityClassName" . | nindent 10 }}
          {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 10 }}
          volumes:
          - name: cache
            persistentVolumeClaim:
              claimName: {{ template "weave.fullname" . }}
          containers:
            - name: weave-cache-clear
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["python", "-c", "from weave import cache; cache.clear_cache()"]
              volumeMounts:
                - name: cache
                  mountPath: /vol/weave/cache
              env:
                - name: WEAVE_LOCAL_ARTIFACT_DIR
                  value: /vol/weave/cache

                {{- include "weave.extraEnv" (dict "global" $.Values.global "local" .Values) | nindent 16 }}
                {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 16 }}
          restartPolicy: Never
{{- end }}