{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weave.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weave.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weave.commonLabels" . | nindent 8 }}
        {{- include "weave.podLabels" . | nindent 8 }}
        {{- include "weave.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}
    spec:
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ include "weave.fullname" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 9994
              protocol: TCP
          env:
            - name: ONLY_SERVICE
              value: weave
            - name: WANDB_BASE_URL
              value: {{ .Values.global.host }}
            - name: WEAVE_LOG_FORMAT
              value: json
            - name: WEAVE_LOCAL_ARTIFACT_DIR
              value: /vol/weave/cache
            - name: WEAVE_AUTH_GRAPHQL_URL
              value: {{ .Values.global.host }}/graphql
            - name: WEAVE_SERVER_NUM_WORKERS
              value: "4"

            {{- include "weave.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          readinessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          startupProbe:
            httpGet:
              path: /__weave/hello
              port: http
            failureThreshold: 12
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: cache
              mountPath: /vol/weave/cache

        - name: {{ include "weave.fullname" . }}-cache-clear
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "-c"]
          args: 
          - |
            import time
            from weave import cache
            print("Starting clear cache job", flush=True)
            while True:
              curTime = time.strftime("%x, %X", time.localtime())
              print("Clearing cache " + curTime, flush=True)
              cache.clear_cache()
              time.sleep({{ .Values.clearCache.hourInterval | default 2 }}*60*60)
            
          env:
            - name: WEAVE_LOCAL_ARTIFACT_DIR
              value: /vol/weave/cache

            {{- include "weave.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}

          volumeMounts:
            - name: cache
              mountPath: /vol/weave/cache

      volumes:
        - name: cache
          emptyDir: 
            sizeLimit: {{ .Values.cache.size | default "5Gi" }}
  
{{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "weave.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "weave.fullname" . }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70