{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weave.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weave.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weave.commonLabels" . | nindent 8 }}
        {{- include "weave.podLabels" . | nindent 8 }}
        {{- include "weave.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}
    spec:
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 9994
              protocol: TCP
          env:
            - name: ONLY_SERVICE
              value: weave
            - name: WANDB_BASE_URL
              value: {{ .Values.global.host }}
            - name: WEAVE_LOG_FORMAT
              value: json
            - name: WEAVE_AUTH_GRAPHQL_URL
              value: {{ .Values.global.host }}/graphql
            - name: wa
              value: 'true'

            {{- include "weave.extraEnv" (dict "global" .Values.global "local" .) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          readinessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          startupProbe:
            httpGet:
              path: /__weave/hello
              port: http
            failureThreshold: 12
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}