---
apiVersion: v1
kind: Service
metadata:
  name: ch-server-headless
  labels:
    app: clickhouse-replica
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      targetPort: http
      port: 8123
      protocol: TCP
    - name: tcp
      targetPort: tcp
      port: 9000
      protocol: TCP
    - name: intrsrvhttp
      targetPort: intrsrvhttp
      port: 9009
      protocol: TCP
  selector:
    app: clickhouse-replica
---
apiVersion: v1
kind: Service
metadata:
  name: ch-server
  labels:
    app: clickhouse-replica
spec:
  clusterIP: None
  selector:
    app: clickhouse-replica
  ports:
    - name: http
      targetPort: http
      port: 8123
      protocol: TCP
    - name: tcp
      targetPort: tcp
      port: 9000
      protocol: TCP
    - name: intrsrvhttp
      targetPort: intrsrvhttp
      port: 9009
      protocol: TCP
