---
# Default values for glue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: wandb/megabinary
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
traceRatio: 0

serviceAccount:
  create: true
  annotations: {}
  name: "glue-sa"
  labels: {}

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

common:
  labels: {}

deployment:
  labels: {}
  annotations: {}

service:
  type: ClusterIP
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 1
    memory: 8G

nodeSelector: {}

tolerations: []

affinity: {}
