apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "otel.commonLabels" . | nindent 4 }}
    {{- include "otel.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels -}}
    {{-   toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.configMap.annotations -}}
    {{-   toYaml .Values.configMap.annotations | nindent 4 }}
    {{- end }}
data:
  config: |
    {{- include "otel.config" . | nindent 4 -}}