apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "otel.labels" . | nindent 4 }}
    {{- include "otel.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9109'
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9109
      protocol: TCP
      name: otel-exporter
    - port: 8125
      protocol: TCP
      name: statsd
    - port: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      protocol: TCP
      name: otlp-http
  selector:
    {{- include "otel.labels" . | nindent 4 }}