---
apiVersion: v1
data:
  launch-config.yaml: |
    {{ required "Please set launchConfig to the contents of your agent config file" .Values.launchConfig | nindent 4 }}
kind: ConfigMap
metadata:
  name: wandb-launch-configmap
  namespace: {{ .Values.namespace }}
...
