---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-agent-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: launch-agent-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: launch-agent-{{ .Release.Name }}
{{- if .Values.agent.labels }}
{{- toYaml .Values.agent.labels | trim | nindent 8 }}
{{- end }}
    spec:
      serviceAccountName: wandb-launch-serviceaccount-{{ .Release.Name }}
      containers:
        - name: launch-agent
          image: {{ .Values.agent.image }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-api-key-{{ .Release.Name }}
                  key: password
            - name: WANDB_LAUNCH_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: WANDB_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: wandb-launch-configmap-{{ .Release.Name }}
                  key: wandb-base-url
            - name: CM_CHECKSUM
              value: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            - name: WANDB_LAUNCH_START_TIMEOUT
              value: "{{ .Values.agent.startTimeout }}"
            - name: WANDB_RELEASE_NAME
              value: "{{ .Release.Name }}"
            {{- if .Values.additionalEnvVars }}
            {{- range .Values.additionalEnvVars }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
            {{- if .Values.additionalSecretEnvVars }}
            {{- range .Values.additionalSecretEnvVars }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: launch-agent-secret-env-vars
                  key: {{ .name }}
            {{- end }}
            {{- end }}
            {{- if and .Values.customCABundle.configMap.name .Values.customCABundle.configMap.key }}
            - name: REQUESTS_CA_BUNDLE
              value: /usr/local/share/ca-certificates/custom-ca.crt
            {{- end }}
          volumeMounts:
            - name: wandb-launch-config
              mountPath: /home/launch_agent/.config/wandb
              readOnly: true
            {{ if .Values.gitCreds}}
            - name: git-creds
              mountPath: /home/launch_agent/
              readOnly: true
            {{ end }}
            {{- if and .Values.customCABundle.configMap.name .Values.customCABundle.configMap.key }}
            - name: custom-cabundle
              mountPath: /usr/local/share/ca-certificates/custom-ca.crt
              subPath: custom-ca.crt
              readOnly: true
            {{ end }}
      volumes:
        - name: wandb-launch-config
          configMap:
            name: wandb-launch-configmap-{{ .Release.Name }}
        {{ if .Values.gitCreds}}
        - name: git-creds
          secret:
            secretName: git-creds
        - name: git-config
          secret:
            secretName: git-config
        {{ end}}
        {{- if and .Values.customCABundle.configMap.name .Values.customCABundle.configMap.key }}
        - name: custom-cabundle
          configMap:
            name: {{ .Values.customCABundle.configMap.name }}
            items:
              - key: {{ .Values.customCABundle.configMap.key }}
                path: custom-ca.crt
        {{- end}}
      nodeSelector:
        {{- toYaml .Values.agent.nodeSelector | nindent 8 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: launch-agent-{{ .Release.Name }}
spec:
  minAvailable: {{ .Values.agent.minAvailable }}
  selector:
    matchLabels:
      app: launch-agent-{{ .Release.Name }}
---