apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-agent
  namespace: wandb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launch-agent
  template:
    metadata:
      labels:
        app: launch-agent
{{- if .Values.agent.labels }}
{{- toYaml .Values.agent.labels | trim | nindent 8 }}
{{- end }}
    spec:
      serviceAccountName: wandb-launch-serviceaccount
      containers:
        - name: launch-agent
          image: {{ .Values.agent.image }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-api-key
                  key: password
            - name: WANDB_LAUNCH_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: wandb-launch-config
              mountPath: /home/launch_agent/.config/wandb
              readOnly: true
            {{ if .Values.gitCreds}}
            - name: git-creds
              mountPath: /home/launch_agent/
              readOnly: true
            - name: git-config
              mountPath: /home/launch_agent/
              readOnly: true
            {{ end }}
      volumes:
        - name: wandb-launch-config
          configMap:
            name: wandb-launch-configmap
        {{ if .Values.gitCreds}}
        - name: git-creds
          secret:
            secretName: git-creds
        - name: git-config
          secret:
            secretName: git-config
        {{ end}}