---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-launch-serviceaccount-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: wandb-launch-agent-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets", "pods/log"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wandb-job-creator-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-role-binding-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: wandb-launch-serviceaccount-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wandb-launch-agent-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
...
{{- define "unique.namespaces" }}
{{- $root := . -}}
{{- $unique := uniq (append .Values.additionalTargetNamespaces .Release.Namespace) }}
{{- range $ns := $unique }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-cluster-role-binding-{{ $root.Release.Name }}
  namespace: {{ $ns }}
subjects:
  - kind: ServiceAccount
    name: wandb-launch-serviceaccount-{{ $root.Release.Name }}
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: wandb-job-creator-{{ $root.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
...
{{- end }}
{{- end }}

{{ include "unique.namespaces" . }}
