apiVersion: v1
kind: Secret
metadata:
  name: wandb-api-key
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  password: {{ required "Please set agent.apiKey to a W&B API key" .Values.agent.apiKey }}

{{- if .Values.gitCreds }}
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  .git-crededentials: {{ .Values.gitCreds }}
  .gitconfig: |
    [credential]
      helper = store
{{ end }}

{{ if .Values.azureStorageAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-access-key
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.azureStorageAccessKey }}
{{ end }}