apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yace.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "yace.commonLabels" . | nindent 4 }}
    {{- include "yace.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels -}}
    {{-   toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.configMap.annotations -}}
    {{-   toYaml .Values.configMap.annotations | nindent 4 }}
    {{- end }}
data:
  config.yml: |
{{- (tpl .Values.config $) | nindent 4 }}