apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yace.serviceAccountName" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "yace.commonLabels" . | nindent 4 }}
    {{- include "yace.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels -}}
    {{-   toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations -}}
    {{-   toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}