nameOverride: ""
fullnameOverride: ""

# These need to be set as well if app name overrides are set
app:
  serviceName: "app"
  clusterDomain: "cluster.local"
  nameOverride: ""
  fullnameOverride: ""

image:
  repository: wandb/weave-trace
  tag: latest
  pullPolicy: Always

tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

common:
  labels: {}
deployment: {}
migration:
  useHook: false
serviceAccount: {}
clusterRole: {}

service:
  type: ClusterIP
  annotations: {}

pod:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 6Gi

datadog:
  enabled: false
  service: "weave-trace"  
  env: "managed-install"
  traceEnabled: false
  logsEnabled: false
  logsInjection: false
  
