nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/local
  tag: latest
  pullPolicy: Always

tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

common:
  labels: {}
deployment: {}
migration: {}
serviceAccount: {}
clusterRole: {}

service:
  type: ClusterIP
  annotations: {}

pod:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 16Gi
