apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-charts
data:
  {{- range $name, $chart := .Values.charts }}
    {{ $name }}.b64: {{ $.Files.Get $chart.path | b64enc }}
  {{- end }}
