{{- if .Values.customCACerts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-ca-certs
data:
  {{- range $index, $pem := .Values.customCACerts }}
  customCA{{$index}}.crt: |-
    {{- range splitList "\n" $pem }}
    {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
