mode: "daemonset"

nameOverride: ""
fullnameOverride: ""

config: {}
presets:
  receivers:
    hostMetrics: false
    logsCollection: false
    kubeletMetrics: false
    kubernetesEvent: false
    kubernetesCluster: false
    statsd: true
    otlp: true

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.97.0
  pullPolicy: IfNotPresent
  # pullSecrets: []

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

service: {}

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

clusterRole:
  annotations: {}
  labels: {}

common:
  labels: {}
  annotations: {}

daemonSet:
  labels: {}
  annotations: {}

deployment:
  labels: {}
  annotations: {}

configMap:
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

serviceAccount:
  create: true

role: {}
roleBinding: {}
