enabled: true

persistence:
  size: 20Gi
  # storageClassName: ""

nameOverride: ""
fullnameOverride: ""

image:
  repository: mysql
  tag: latest
  pullPolicy: Always

tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []
common: {}

service:
  type: ClusterIP
  annotations: {}
  labels: {}

pod:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 8Gi
