replicaCount: 1

image:
  repository: wandb/controller
  tag: latest
  pullPolicy: Always
  pullSecrets: []

extraEnvs: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 300Mi

podAnnotations: {}

nameOverride: wandb
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true

clusterRole:
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]

airgapped: false
