replicaCount: 1

image:
  repository: wandb/controller
  tag: latest
  pullPolicy: Always
  pullSecrets: []

extraEnvs: []

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podAnnotations: {}

nameOverride: wandb
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true
