replicaCount: 1

image:
  repository: wandb/controller
  tag: latest
  pullPolicy: Always
  pullSecrets: []

extraEnvs: []

resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 250Mi

podAnnotations: {}

nameOverride: wandb
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true
