replicaCount: 1

image:
  repository: wandb/controller
  tag: dev
  pullPolicy: IfNotPresent
  pullSecrets: []

extraEnvs: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 300Mi

podAnnotations: {}

nameOverride: wandb
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true

clusterRole:
  rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
        - secrets
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - apiGroups:
        - app
      resources:
        - deployments
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases/finalizers
      verbs:
        - update
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases/status
      verbs:
        - get
        - patch
        - update

airgapped: false
namespaceIsolation:
  enabled: false
  additionalNamespaces: []