replicaCount: 1

image:
  repository: wandb/controller
  tag: latest
  pullPolicy: Always
  pullSecrets: []

extraEnvs: []
role:
  rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
        - persistentvolumeclaims
        - secrets
        - serviceaccounts
        - services
        - events
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - ""
      resources:
        - endpoints
        - ingresses
        - nodes
        - nodes/metrics
        - nodes/spec
        - nodes/stats
        - nodes/proxy
        - namespaces
        - namespaces/status
        - pods
        - pods/log
        - pods/status
        - resourcequotas
        - replicationcontrollers
        - replicationcontrollers/status
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
        - statefulsets
        - daemonsets
        - replicasets
        - controllerrevisions
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments/status
        - statefulsets/status
        - daemonsets/status
        - replicasets/status
      verbs:
        - get
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases/finalizers
      verbs:
        - update
    - apiGroups:
        - apps.wandb.com
      resources:
        - weightsandbiases/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - autoscaling
      resources:
        - horizontalpodautoscalers
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - apiGroups:
        - batch
      resources:
        - cronjobs
        - jobs
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - events.k8s.io
      resources:
        - events
      verbs:
        - watch
        - list
    - apiGroups:
        - extensions
      resources:
        - daemonsets
        - deployments
        - ingresses
        - replicasets
        - ingresses/status
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - networking.k8s.io
      resources:
        - ingresses
        - networkpolicies
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - networking.k8s.io
      resources:
        - ingresses/status
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - roles
        - rolebindings
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 300Mi

podAnnotations: {}

nameOverride: wandb
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true

airgapped: false
namespaceIsolation:
  enabled: false
  additionalNamespaces: []

customCACerts: []
