apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/log
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  - bindings
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - ingresses
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - apps.wandb.com
  resources:
  - weightsandbiases
  - weightsandbiases/status
  - weightsandbiases/finalizers
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resourceNames: []
  resources:
  - prioritylevelconfigurations
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create

- apiGroups:
  - policy
  resourceNames: []
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - create