apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "wandb.fullname" . }}-secret-manager
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]