---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wandb.secretManagerRoleBindingName" . }}
  labels:
  {{- include "wandb.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wandb.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "wandb.secretManagerRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
