apiVersion: v1
kind: ConfigMap
metadata:
  name: keeper-config
data:
  ch-keeper-0.xml: |
    ch-keeper-0.xml: |
      <clickhouse replace="true">
          <path>/var/lib/clickhouse/coordination/keeper</path>
          <logger>
              <level>{{ .Values.logger.level }}</level>
              <console>{{ .Values.logger.console }}</console>
              <log remove="remove"/>
              <errorlog remove="remove"/>
              <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
              <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
              <size>1000M</size>
              <count>3</count -->
          </logger>
          <listen_host>{{ .Values.listen_host }}</listen_host>
          <keeper_server>
              <tcp_port>{{ .Values.keeper_server.tcp_port }}</tcp_port>
              <http_control>
                <port>{{ .Values.keeper_server.http_control.port }}</port>
                <readiness><endpoint>{{ .Values.keeper_server.http_control.readiness.endpoint }}</endpoint></readiness>
              </http_control>
              <server_id>0</server_id>
              <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
              <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
              <coordination_settings>
                  <operation_timeout_ms>{{ .Values.coordination_settings.operation_timeout_ms }}</operation_timeout_ms>
                  <session_timeout_ms>{{ .Values.coordination_settings.session_timeout_ms }}</session_timeout_ms>
                  <raft_logs_level>{{ .Values.coordination_settings.raft_logs_level }}</raft_logs_level>
              </coordination_settings>
              <raft_configuration>
                  {{- range $index, $server := .Values.raft_configuration.servers }}
                  <server>
                      <id>{{ $server.id }}</id>
                      <hostname>{{ $server.hostname }}</hostname>
                      <port>{{ $server.port }}</port>
                  </server>
                  {{- end }}
              </raft_configuration>
          </keeper_server>
      </clickhouse>
    ch-keeper-1.xml: |
      <clickhouse replace="true">
          <path>/var/lib/clickhouse/coordination/keeper</path>
          <logger>
              <level>{{ .Values.logger.level }}</level>
              <console>{{ .Values.logger.console }}</console>
              <log remove="remove"/>
              <errorlog remove="remove"/>
              <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
              <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
              <size>1000M</size>
              <count>3</count -->
          </logger>
          <listen_host>{{ .Values.listen_host }}</listen_host>
          <keeper_server>
              <tcp_port>{{ .Values.keeper_server.tcp_port }}</tcp_port>
              <http_control>
                <port>{{ .Values.keeper_server.http_control.port }}</port>
                <readiness><endpoint>{{ .Values.keeper_server.http_control.readiness.endpoint }}</endpoint></readiness>
              </http_control>
              <server_id>1</server_id>
              <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
              <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
              <coordination_settings>
                  <operation_timeout_ms>{{ .Values.coordination_settings.operation_timeout_ms }}</operation_timeout_ms>
                  <session_timeout_ms>{{ .Values.coordination_settings.session_timeout_ms }}</session_timeout_ms>
                  <raft_logs_level>{{ .Values.coordination_settings.raft_logs_level }}</raft_logs_level>
              </coordination_settings>
              <raft_configuration>
                  {{- range $index, $server := .Values.raft_configuration.servers }}
                  <server>
                      <id>{{ $server.id }}</id>
                      <hostname>{{ $server.hostname }}</hostname>
                      <port>{{ $server.port }}</port>
                  </server>
                  {{- end }}
              </raft_configuration>
          </keeper_server>
      </clickhouse>
    ch-keeper-2.xml: |
      <clickhouse replace="true">
          <path>/var/lib/clickhouse/coordination/keeper</path>
          <logger>
              <level>{{ .Values.logger.level }}</level>
              <console>{{ .Values.logger.console }}</console>
              <log remove="remove"/>
              <errorlog remove="remove"/>
              <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
              <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
              <size>1000M</size>
              <count>3</count -->
          </logger>
          <listen_host>{{ .Values.listen_host }}</listen_host>
          <keeper_server>
              <tcp_port>{{ .Values.keeper_server.tcp_port }}</tcp_port>
              <http_control>
                <port>{{ .Values.keeper_server.http_control.port }}</port>
                <readiness><endpoint>{{ .Values.keeper_server.http_control.readiness.endpoint }}</endpoint></readiness>
              </http_control>
              <server_id>2</server_id>
              <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
              <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
              <coordination_settings>
                  <operation_timeout_ms>{{ .Values.coordination_settings.operation_timeout_ms }}</operation_timeout_ms>
                  <session_timeout_ms>{{ .Values.coordination_settings.session_timeout_ms }}</session_timeout_ms>
                  <raft_logs_level>{{ .Values.coordination_settings.raft_logs_level }}</raft_logs_level>
              </coordination_settings>
              <raft_configuration>
                  {{- range $index, $server := .Values.raft_configuration.servers }}
                  <server>
                      <id>{{ $server.id }}</id>
                      <hostname>{{ $server.hostname }}</hostname>
                      <port>{{ $server.port }}</port>
                  </server>
                  {{- end }}
              </raft_configuration>
          </keeper_server>
      </clickhouse>
