---
apiVersion: v1
kind: Service
metadata:
  name: keeper-headless
  labels:
    app: keeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: keeper
  ports:
    - name: keeper
      targetPort: keeper
      port: 9181
      protocol: TCP
    - name: http
      targetPort: http
      port: 9182
      protocol: TCP
    - name: raft
      targetPort: raft
      port: 9234
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    app: keeper
spec:
  clusterIP: None  
  selector:
    app: keeper
  ports:
    - name: keeper
      targetPort: keeper
      port: 9181
      protocol: TCP
    - name: http
      targetPort: http
      port: 9182
      protocol: TCP
    - name: raft
      targetPort: raft
      port: 9234
      protocol: TCP
