apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "prometheus.commonLabels" . | nindent 4 }}
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  {{ include "wandb.storageClass" . | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
