apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "prometheus.labels" . | nindent 4 }}
    {{- include "prometheus.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "prometheus.labels" . | nindent 4 }}