{{- if .Values.autoscaling.vertical.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "wandb-service.fullname" . }}
  labels:
    {{- include "wandb-service.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "wandb-service.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.autoscaling.vertical.updateMode }}
  resourcePolicy:
    containerPolicies:
      {{- with .Values.autoscaling.vertical.containerPolicies }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
