apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.fullname" . }}-data
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "mysql.commonLabels" . | nindent 4 }}
    {{- include "mysql.labels" . | nindent 4 }}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "wandb.storageClass" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
