{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weaveTraces.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTraces.commonLabels" . | nindent 4 }}
    {{- include "weaveTraces.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weaveTraces.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weaveTraces.commonLabels" . | nindent 8 }}
        {{- include "weaveTraces.podLabels" . | nindent 8 }}
        {{- include "weaveTraces.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}
    spec:
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ include "weaveTraces.fullname" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: WF_TRACE_SERVER_URL
              value: "{{ .Values.global.host }}/traces"
            - name: WANDB_BASE_URL
              value: http://{{ include "weaveTraces.appFullname" . }}.{{ $.Release.Namespace }}.svc.{{ .Values.app.clusterDomain }}:8080/graphql
            - name: WF_CLICKHOUSE_HOST
              value: "{{ .Values.global.clickhouse.host }}"
            - name: WF_CLICKHOUSE_PORT
              value: "{{ .Values.global.clickhouse.port }}"
            - name: WF_CLICKHOUSE_DATABASE
              value: "{{ .Values.global.clickhouse.database }}"
            - name: WF_CLICKHOUSE_USER
              value: "{{ .Values.global.clickhouse.user }}"
            - name: WF_CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: CLICKHOUSE_PASSWORD
            {{- if .Values.datadog.enabled }}
            - name: DD_SERVICE
              value: "{{ .Values.datadog.service }}"
            - name: DD_ENV
              value: "{{ .Values.datadog.env }}"
            - name: DD_TRACE_ENABLED
              value: "{{ .Values.datadog.traceEnabled }}"
            - name: DD_LOGS_ENABLED
              value: "{{ .Values.env.logsEnabled }}"
            - name: DD_LOGS_INJECTION
              value: "{{ .Values.env.logsInjection }}"
            {{- end }}
            {{- include "weaveTraces.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          {{- if not .Values.datadog.enabled }}
          command:
            - uvicorn
          args:
            - "src.trace_server:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 2
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 12
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "weaveTraces.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTraces.commonLabels" . | nindent 4 }}
    {{- include "weaveTraces.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "weaveTraces.fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
        