apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaveTraces.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTraces.labels" . | nindent 4 }}
    {{- include "weaveTraces.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8722
      targetPort: 8080
      protocol: TCP
      name: weave-traces
  selector:
    {{- include "weaveTraces.labels" . | nindent 4 }}