global:
  bucket:
    provider: "s3"
    name: "minio.minio.svc.cluster.local:9000/bucket"
    region: "us-east-1"
    accessKey: "minio"
    secretKey: "minio123"

app:
  extraEnv:
    GLOBAL_ADMIN_API_KEY: "test-api-key"
    GORILLA_INSECURE_ALLOW_API_KEY_ADMIN_ACCESS: "true"

ingress:
  install: false
  create: false

mysql:
  install: true
redis:
  install: true
