enabled: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/console
  tag: latest
  pullPolicy: Always
  # pullSecrets: []

# Tolerations for pod scheduling
tolerations: []

extraEnv:
  TESTING: true
extraEnvFrom: {}

extraCors: []

common: {}
deployment: {}
serviceAccount: {}
clusterRole: {}

service:
  type: ClusterIP

pod:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

resources:
  # We usually recommend not to specify default resources and to leave this as a
  # conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 500Mi
