enabled: true

nameOverride: ""
fullnameOverride: ""

config: {}

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.87.0
  pullPolicy: IfNotPresent
  # pullSecrets: []

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

common:
  labels: {}

daemonSet:
  labels: {}
  annotations: {}

configMap:
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

serviceAccount:
  create: true

role: {}
roleBinding: {}
