enabled: true

nameOverride: ""
fullnameOverride: ""

config:
  exporters:
    datadog:
      api:
        site: datadoghq.com
        key: 28f4f4f706ab89f3bdeceae0e81fd950
  service:
    pipelines:
      metrics/datadog:
        exporters: [datadog]
        processors: [memory_limiter, batch, k8sattributes]
        receivers: [hostmetrics, k8s_cluster, kubeletstats]

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.87.0
  pullPolicy: IfNotPresent
  # pullSecrets: []

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

service: {}

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

clusterRole:
  annotations: {}
  labels: {}

common:
  labels: {}
  annotations: {}

daemonSet:
  labels: {}
  annotations: {}

configMap:
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

serviceAccount:
  create: true

role: {}
roleBinding: {}
