apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-exporter.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "node-exporter.labels" . | nindent 4 }}
    {{- include "node-exporter.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9100'
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: node-exporter
  selector:
    {{- include "node-exporter.labels" . | nindent 4 }}