{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cron.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "cron.labels" . | nindent 4 }}
    {{- if .Values.cronjob.labels -}}
    {{-   toYaml .Values.cronjob.labels | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: {{ .Values.command }}
              env:
              - name: ONLY_SERVICE
                value: gorilla-glue-execute
              - name: LOGGING_ENABLED
                value: 'true'
              - name: MYSQL_PORT
                value: "{{ include "wandb.mysql.port" . }}"
              - name: MYSQL_HOST
                value: "{{ include "wandb.mysql.host" . }}"
              - name: MYSQL_DATABASE
                value: "{{ include "wandb.mysql.database" . }}"
              - name: MYSQL_USER
                value: "{{ include "wandb.mysql.user" . }}"
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "wandb.mysql.passwordSecret" . }}
                    key:  MYSQL_PASSWORD
              - name: MYSQL
                value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)"

              {{- if ne (include "wandb.redis.password" .) "" }}
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "wandb.redis.passwordSecret" . }}
                    key: REDIS_PASSWORD
              {{- end }}
              - name: REDIS_PORT
                value: "{{ include "wandb.redis.port" . }}"
              - name: REDIS_HOST
                value: "{{ include "wandb.redis.host" . }}"
              - name: REDIS
                value: "{{ include "parquet.redis" . | trim }}"

              - name: GORILLA_SETTINGS_CACHE
                value: "{{ include "parquet.redis" . | trim }}"

              - name: BUCKET
                value: "{{ include "parquet.bucket" . }}"
              - name: BUCKET_QUEUE
                value: "internal://"
              - name: AWS_REGION
                value: {{ .Values.global.bucket.region }}
              - name: AWS_S3_KMS_ID
                value: "{{ .Values.global.bucket.kmsKey }}"
              - name: AZURE_STORAGE_KEY
                valueFrom:
                  secretKeyRef:
                    name: "{{ include "wandb.bucket.secret" . }}"
                    key: ACCESS_KEY
                    optional: true

              {{- include "cron.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
              {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}

              resources:
                {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
