{{- if .Values.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cron.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: 
                {{ toYaml .Values.command | nindent 16 }}
          restartPolicy: Never
# TODO: Env - Look at gorilla glue config
# TODO: NodeSelectors
# TODO: Labels
# TODO: Annotations
{{- end }}
