{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "console.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "console.commonLabels" . | nindent 4 }}
    {{- include "console.labels" . | nindent 4 }}
    {{- if .Values.clusterRole.labels -}}
    {{-   toYaml .Values.clusterRole.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.clusterRole.annotations -}}
    {{-   toYaml .Values.clusterRole.annotations | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - ""
      - apps
      - apps.wandb.com
      - autoscaling
      - policy
      - networking.k8s.io
      - metrics.k8s.io
      - flowcontrol.apiserver.k8s.io
      - rbac.authorization.k8s.io
    resources:
      - pods
      - deployments
      - bindings
      - configmaps
      - endpoints
      - events
      - namespaces
      - pods/logs
      - pods
      - replicationcontrollers
      - secrets
      - serviceaccounts
      - weightsandbiases.apps.wandb.com
      - controllerrevisions.apps
      - deployments.apps
      - replicasets.apps
      - statefulsets.apps
      - horizontalpodautoscalers.autoscaling
      - prioritylevelconfigurations.flowcontrol.apiserver.k8s.io
      - nodes.metrics.k8s.io
      - ingressclasses.networking.k8s.io 
      - ingresses.networking.k8s.io
      - poddisruptionbudgets.policy  
      - roles.rbac.authorization.k8s.io
    verbs: [get, list, watch, create, update, patch, delete]
{{- end }}