{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "console.commonLabels" . | nindent 4 }}
    {{- include "console.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "console.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "console.commonLabels" . | nindent 8 }}
        {{- include "console.podLabels" . | nindent 8 }}
        {{- include "console.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "console.fullname" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: AUTH_SERVICE
              value: {{ .Release.Name }}-app:8080
            - name: OPERATOR_NAMESPACE
              value: {{ .Values.global.operator.namespace }}
            - name: RELEASE_NAME
              value: {{ $.Release.Name }}
            - name: RELEASE_NAMESPACE
              value: {{ $.Release.Namespace }}
            - name: PROMETHEUS_SERVER
              value: "http://{{ $.Release.Name }}-prometheus-server"

            - name: G_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            {{- include "console.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /console/api/healthz
              port: http
          readinessProbe:
            httpGet:
              path: /console/api/ready
              port: http
          startupProbe:
            httpGet:
              path: /console/api/ready
              port: http
            failureThreshold: 120

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
