enabled: true

nameOverride: "prometheus-mysql-exporter"
fullnameOverride: ""

image:
  repository: prom/mysqld-exporter
  tag: latest
  pullPolicy: Always

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

pod:
  securityContext: {}
  labels: {}
  annotations: {}

common:
  labels: {}

deployment:
  labels: {}
  annotations: {}

service:
  type: ClusterIP
  annotations: {}
  labels: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a
  # conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 300m
    memory: 200Mi
