enabled: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/local
  tag: latest
  pullPolicy: Always

tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

common: {}
deployment: {}
serviceAccount: {}
clusterRole: {}

service:
  type: ClusterIP
  annotations: {}

pod:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"

resources:
  # We usually recommend not to specify default resources and to leave this as a
  # conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 16Gi

persistence:
  provider: ""
  accessMode: ReadWriteMany
  # storageClassName: ""
  size: 20Gi
  efs:
    fileSystemId: ""
