apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otelAgent.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "otelAgent.commonLabels" . | nindent 4 }}
    {{- include "otelAgent.labels" . | nindent 4 }}
    {{- if .Values.clusterRole.labels -}}
    {{-   toYaml .Values.clusterRole.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.clusterRole.annotations -}}
    {{-   toYaml .Values.clusterRole.annotations | nindent 4 }}
    {{- end }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "otelAgent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "otelAgent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
