apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelAgent.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "otelAgent.commonLabels" . | nindent 4 }}
    {{- include "otelAgent.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels -}}
    {{-   toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.configMap.annotations -}}
    {{-   toYaml .Values.configMap.annotations | nindent 4 }}
    {{- end }}
data:
  config: |
    {{- include "otelAgent.config" . | nindent 4 -}}