enabled: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/local
  tag: latest
  pullPolicy: Always
  # pullSecrets: []

schedule: "*/5 * * * *"  # Every 5 minutes
command: ["megabinary", "glue", "execute", "EXPORTHISTORYTOPARQUET"]

# Tolerations for pod scheduling
tolerations: []

extraEnv:
  TESTING: true
extraEnvFrom: {}

extraCors: []

pod:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  labels: {}
  annotations: {}

common:
  labels: {}

deployment:
  labels: {}
  annotations: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 8Gi

role: {}
roleBinding: {}
