{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "wandb-base.fullname" .}}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- with .Values.helmHookAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
    {{- with .Values.role.rules }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
