{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wandb-base.fullname" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wandb-base.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "wandb-base.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
