{{- if .Values.service.enabled }}
{{- if .Values.global.createGCPLoadBalancerBackend }}
{{- if eq .Values.global.cloudProvider "gcp" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "wandb-base.fullname" . }}-backend-config
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
spec:
  timeoutSec: 120
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wandb-base.fullname" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if eq .Values.global.cloudProvider "aws" }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ready
    {{- if and .Values.global.createGCPLoadBalancerBackend (eq .Values.global.cloudProvider "gcp") }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ include "wandb-base.fullname" . }}-backend-config"}'
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "wandb-base.selectorLabels" . | nindent 4 }}
{{- end }}
