{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wandb-base.fullname" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "wandb-base.selectorLabels" . | nindent 4 }}
  {{ end }}