{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wandb-base.serviceAccountName" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if or .Values.helmHookAnnotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.helmHookAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
