apiVersion: apps.wandb.com/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec: {{ toYaml .Values.spec | nindent 2 }}
