apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.commonLabels" . | nindent 4 }}
    {{- include "nginx.labels" . | nindent 4 }}
    {{- if .Values.role.labels -}}
    {{-   toYaml .Values.role.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.role.annotations -}}
    {{-   toYaml .Values.role.annotations | nindent 4 }}
    {{- end }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "nginx.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx.fullname" . }}
    namespace: {{ .Release.Namespace }}