apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "nginx.labels" . | nindent 4 }}
    {{- include "nginx.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "nginx.labels" . | nindent 4 }}