agent:
  apiKey: local-...
  image: wandb/launch-agent-dev:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

namespace: wandb-launch

launchConfig:
  base_url: https://api.wandb.ai
  entity: entity-name
  max_jobs: -1
  queues:
    - default
  environment:
    type: local
  registry:
    type: local
  builder:
    type: docker

volcano: true

gitCreds: |

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account:
