agent:
  apiKey: "<an-api-key>"
  image: wandb/launch-agent:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

namespace: wandb

additionalTargetNamespaces:
  - default
  - wandb

launchConfig: |
  queues: ["default"]

volcano: true

gitCreds: |

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account:
