apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.labels" . | nindent 4 }}
    {{- if .Values.role.labels -}}
    {{-   toYaml .Values.role.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.role.annotations -}}
    {{-   toYaml .Values.role.annotations | nindent 4 }}
    {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]